name: futurejd
region: nyc
services:
  - build_command: pip install -r requirements.txt
    environment_slug: python
    github:
      repo: https://github.com/zwglanz/AIWebsite.git
      branch: main
    http_port: 8000
    name: service-name